apiVersion: v1
kind: Service
metadata:
  name: springboot-jar-service
spec:
  type: NodePort
  selector:
    app: springboot-jar-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
