apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-jar-deployment
  labels:
    app: springboot-jar-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-jar-app
  template:
    metadata:
      labels:
        app: springboot-jar-app
    spec:
      containers:
        - name: springboot-jar-container
          image: uday07/springboot-docker-jar-demo
          ports:
            - containerPort: 8080